### PR TITLE
Upgrade to Aff 4.0

### LINKED ISSUE #17: Needs Aff 4.0 version
I'll try to look into this myself too, just needs to be some time to have this library updated and put it into a Aff 4.0-compatible package set

### PR DESCRIPTION
**Pull request by justinwoo**
Upgrades to Aff 4.0

fixes #17

### CODE REVIEW

**Comment by justinwoo** [comment]
Can someone run the tests to see if anything breaks?

**Comment by anttih** [comment]
The tests seem to hang after outputting

```
connection string
  ✓︎ should build one from the connection record
```

Could this be a ps-spec thing?

**Comment by anttih** [comment]
Ah, I think it's the `connect'` which returns an `Aff`.

Edit: that uses the FFI.

**Comment by anttih** [comment]
There's actually quite a few functions defined through the FFI that return an Aff.

**Comment by tonyd256** [comment]
Any idea when this might get implemented? I've been trying to do it myself all morning but I'm too new to purescript and this library to get it working.

**Comment by justinwoo** [comment]
Closing since we have #19

**Pull request closed without merging**
