### PR TITLE
V0.15.0 update

### PR DESCRIPTION
**Pull request by sigma-andex**
v0.15.0 update with a couple of improvements to facilitate the transition

### CODE REVIEW

**Comment by sigma-andex** [comment]
@epost do you still maintain this library?

**Comment by epost** [comment]
Hey @sigma-andex! Yes, I'll have a closer look at this asap. It looks great, thanks! 🙏

**Comment by sigma-andex** [comment]
@epost would you be interested in transferring  the maintainership of this repo?

**Comment by epost** [comment]
Hi @sigma-andex, sorry about the long wait. I just had some time this afternoon to try out your PR, but I see that you've closed and deleted it. However, I'm still interested in merging it. Would you be interested in resubmitting?

**Comment by sigma-andex** [comment]
Hi @epost , no worries. I couldn't wait so in the meantime I have forked your project as [yoga-postgres](https://github.com/rowtype-yoga/purescript-yoga-postgres) that I will continue to work on. I have reopened the branch and created a new PR. Feel free to edit it and merge as you wish.

**Comment by epost** [comment]
Wonderful, thanks for your time and effort @sigma-andex! I'm running into some issues during building and test execution, so I'm looking into fixing those.

**Pull request closed without merging**
